
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceciklfwvpmrzdwqgasd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlY2lrbGZ3dnBtcnpkd3FnYXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MTIzMjksImV4cCI6MjA1MjM4ODMyOX0.qX0-BHKSVHolDEyXB0lo689itIbSp4KRHnBDw2vEHQM";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
);
